# Generated by Django 4.2.28 on 2026-04-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("razorpay", "Razorpay"), ("cod", "Cash on Delivery")],
                default="razorpay",
                max_length=20,
            ),
        ),
    ]
